-- Generated by matugen -- Hyprland Lua colors (current snapshot)
-- Regenerated automatically on wallpaper changes via matugen
-- (templates/hyprland/colors.lua -> this file).

hl.config({
    general = {
        col = {
            active_border   = "rgba(979087AA)",
            inactive_border = "rgba(4b463eAA)",
        },
    },
    misc = {
        background_color = "rgba(141312FF)",
    },
})

hl.window_rule({
    name  = "matugen-pin-border",
    match = { pin = true },
    border_color = {
        colors = {
            "rgba(fdf1e3AA)",
            "rgba(fdf1e377)",
        },
    },
})