-- Stage 0 scaffold: minimal Lua config to prove the Lua config manager and the
-- test harness. The live session does NOT use this file. It is only exercised via:
--   Hyprland --verify-config -c <this file>
--   Hyprland -c <this file>          (nested instance inside the running session)

hl.config({ autogenerated = false })

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})