-- Hyprland Lua config entry (migration of hyprland.conf)
-- STAGED: not used by the live session until cutover (still only reachable
-- via the verify-config gate / -c flag).

hl.config({ autogenerated = false })

require("general")
require("custom.general")
require("env")
require("animations")
require("monitors")
require("gestures")
require("workspaces")

-- Input block that lived inline in hyprland.conf (applied after modules)
hl.config({
    input = {
        kb_layout  = "us,ara",
        kb_variant = "",
        kb_options = "grp:win_space_toggle",
    },
})