-- Hyprland Lua config entry (migration of hyprland.conf)
-- STAGED: not used by the live session until cutover (still only reachable
-- via the verify-config gate / -c flag).

hl.config({ autogenerated = false })

-- Order mirrors the `source=` lines of hyprland.conf.
require("env")
require("general")
require("animations")
require("rules")
require("custom.general")
require("custom.rules")
require("transparent.vscode")
require("transparent.antigravity")
require("transparent.kitty")
require("monitors")
require("gestures")
require("workspaces")
-- keybinds land in stage 5, matugen colors in stage 6

-- Input block that lived inline in hyprland.conf (applied after modules)
hl.config({
    input = {
        kb_layout  = "us,ara",
        kb_variant = "",
        kb_options = "grp:win_space_toggle",
    },
})