-- Hyprland Lua config entry -- PRODUCTION (cutover)
-- Loads the module tree from the `lua/` subdirectory (dotfiles-backed).
-- Created at stage 9; Hyprland prefers this file over hyprland.conf.

hl.config({ autogenerated = false })

require("lua.env")
require("lua.general")
require("lua.execs")
require("lua.animations")
require("lua.rules")
require("lua.colors")
require("lua.keybinds")
require("lua.custom.general")
require("lua.custom.rules")
require("lua.transparent.vscode")
require("lua.transparent.antigravity")
require("lua.transparent.kitty")
require("lua.monitors")
require("lua.gestures")
require("lua.workspaces")

-- Input block that lived inline in hyprland.conf (applied after modules)
hl.config({
    input = {
        kb_layout  = "us,ara",
        kb_variant = "",
        kb_options = "grp:win_space_toggle",
    },
})