windowrule = opacity 0.99 0.99 override, match:class ^(kitty)$



blurls = kitty

decoration { 
  blur {
      enabled = true
      size = 2
      passes = 3
      new_optimizations = true
      ignore_opacity = true
    }
}
