general {
    col.active_border = rgba(979087AA)
    col.inactive_border = rgba(4b463eAA)
}

misc {
    background_color = rgba(141312FF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(141312FF)
        col.text = rgba(e6e1dfFF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(e6e1df), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(e6e1df), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(e6e1df), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrule {
  name = windowrule-1
  border_color = rgba(fdf1e3AA) rgba(fdf1e377)
  match:pin = 1
}
